<?php

use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder {

    /**
     * Seed the application's database.
     *
     * @return void
     */

    public function run() {
        
        DB::table('users')->insert([
            [
             'nome' => 'lore',
             'cognome' => 'lore',               
             'data_nascita' => date("Y-m-d"),
             'genere' => 'maschio',
             'email' => 'lore@lore.it',
             'telefono' => '3980901389',
             'username' => 'lorelore',
             'password' => Hash::make('Njpwskf4'),
             'role' => 'locatore',
             'created_at' => date("Y-m-d H:i:s"),
             'updated_at' => date("Y-m-d H:i:s")],
            
            [
             'nome' => 'lario',
             'cognome' => 'lario',               
             'data_nascita' => date("Y-m-d"),
             'genere' => 'maschio',
             'email' => 'lario@lario.it',
             'telefono' => '3182201389',
             'username' => 'lariolario',
             'password' => Hash::make('Njpwskf4'),
             'role' => 'locatario',
             'created_at' => date("Y-m-d H:i:s"),
             'updated_at' => date("Y-m-d H:i:s")],
            
            [
             'nome' => 'admin',
             'cognome' => 'admin',               
             'data_nascita' => date("Y-m-d"),
             'genere' => 'maschio',
             'email' => 'admin@admin.it',
             'telefono' => '3280912439',
             'username' => 'adminadmin',
             'password' => Hash::make('Njpwskf4'),
             'role' => 'admin',
             'created_at' => date("Y-m-d H:i:s"),
             'updated_at' => date("Y-m-d H:i:s")],
            
            [
             'nome' => 'mario',
             'cognome' => 'mario',               
             'data_nascita' => date("Y-m-d"),
             'genere' => 'maschio',
             'email' => 'lario@lario.it',
             'telefono' => '3182201389',
             'username' => 'mariomario',
             'password' => Hash::make('mariomario'),
             'role' => 'locatario',
             'created_at' => date("Y-m-d H:i:s"),
             'updated_at' => date("Y-m-d H:i:s")],
            
            [
             'nome' => 'catore',
             'cognome' => 'catore',               
             'data_nascita' => date("Y-m-d"),
             'genere' => 'maschio',
             'email' => 'lario@lario.it',
             'telefono' => '3182201389',
             'username' => 'catore',
             'password' => Hash::make('catore'),
             'role' => 'locatore',
             'created_at' => date("Y-m-d H:i:s"),
             'updated_at' => date("Y-m-d H:i:s")],
            
            [
             'nome' => 'min',
             'cognome' => 'admin',               
             'data_nascita' => date("Y-m-d"),
             'genere' => 'maschio',
             'email' => 'lario@lario.it',
             'telefono' => '3182201389',
             'username' => 'minmin',
             'password' => Hash::make('minmin'),
             'role' => 'admin',
             'created_at' => date("Y-m-d H:i:s"),
             'updated_at' => date("Y-m-d H:i:s")],
        ]);

        DB::table('annunci')->insert([
            ['AnnuncioId' => '1',
             'user_id' => '1',
             'citta' => 'Ancona',               
             'zona_quartiere' => 'Q1',
             'indirizzo' => 'via brecce bianche 12',
             'descrizione' => 'appartamento',
             'importo' => '750',
             'dimensione' => '70',
             'tipologia' => 'Appartamento',
             'data_inizio_disponibilita' => date("2022-05-15"),
             'data_fine_disponibilita' => date("2023-06-15"),
             'servizi_inclusi' => 'Wi-fi,Parcheggio Riservato,Ascensore',
             'eta_minima' => '19',
             'genere_richiesto' => 'uomini',
             'assegnato' => '0',               
             'data_assegnazione' => null,
             'immagine' => '1.jpg',
             'numero_posti_letto_totali' => 5,
             'C_numero_posti_letto_in_camera' => null,
             'A_numero_camere' => '3',
             'A_locali_presenti' => 'Cucina,Bagno Singolo,Garage',
             'created_at' => date("Y-m-d H:i:s"),
             'updated_at' => date("Y-m-d H:i:s")],
            
            ['AnnuncioId' => '2',
             'user_id' => '5',
             'citta' => 'Ancona',               
             'zona_quartiere' => 'Q2',
             'indirizzo' => 'via flavia 25',
             'descrizione' => 'camera spaziosa',
             'importo' => '220',
             'dimensione' => '18',
             'tipologia' => 'Posto Letto',
             'data_inizio_disponibilita' => date("2022-02-17"),
             'data_fine_disponibilita' => date("2023-03-17"),
             'servizi_inclusi' => 'Angolo Studio,Minibar,Wi-fi',
             'eta_minima' => '19',
             'genere_richiesto' => null,
             'assegnato' => '1',               
             'data_assegnazione' => date("2022-05-31"),
             'immagine' => '2.jpg',
             'numero_posti_letto_totali' => 6,
             'C_numero_posti_letto_in_camera' => 2,
             'A_numero_camere' => null,
             'A_locali_presenti' => null,
             'created_at' => date("Y-m-d H:i:s"),
             'updated_at' => date("Y-m-d H:i:s")],
            
            ['AnnuncioId' => '3',
            'user_id' => '5',
             'citta' => 'Jesi',               
             'zona_quartiere' => 'Centrale',
             'indirizzo' => 'viale della vittoria 25',
             'descrizione' => 'camera spaziosa',
             'importo' => '300',
             'dimensione' => '20',
             'tipologia' => 'Posto Letto',
             'data_inizio_disponibilita' => date("2022-01-17"),
             'data_fine_disponibilita' => date("2023-01-17"),
             'servizi_inclusi' => 'lavastoviglie garage',
             'eta_minima' => '19',
             'genere_richiesto' => 'donne',
             'assegnato' => '0',               
             'data_assegnazione' => null,
             'immagine' => '3.jpg',
              'numero_posti_letto_totali' => 4,
             'C_numero_posti_letto_in_camera' => 1,
             'A_numero_camere' => null,
             'A_locali_presenti' => null,
             'created_at' => date("Y-m-d H:i:s"),
             'updated_at' => date("Y-m-d H:i:s")],
            
            
            ['AnnuncioId' => '4',
             'user_id' => '1',
             'citta' => 'Ancona',               
             'zona_quartiere' => 'Q2',
             'indirizzo' => 'via flavia 25',
             'descrizione' => 'camera spaziosa',
             'importo' => '220',
             'dimensione' => '18',
             'tipologia' => 'Posto Letto',
             'data_inizio_disponibilita' => date("2022-02-17"),
             'data_fine_disponibilita' => date("2023-03-17"),
             'servizi_inclusi' => 'lavastoviglie garage',
             'eta_minima' => '19',
             'genere_richiesto' => null,
             'assegnato' => '0',               
             'data_assegnazione' => null,
             'immagine' => '4.jpg',
             'numero_posti_letto_totali' => null,
             'C_numero_posti_letto_in_camera' => null,
             'A_numero_camere' => '1',
             'A_locali_presenti' => 'Cucina',
             'created_at' => date("Y-m-d H:i:s"),
             'updated_at' => date("Y-m-d H:i:s")],
            
            ['AnnuncioId' => '5',
           'user_id' => '1',
             'citta' => 'Ancona',               
             'zona_quartiere' => 'Semicentro',
             'indirizzo' => 'via maggini 18',
             'descrizione' => 'Questa nuova struttura ricettiva, dalle linee sobrie ed essenziali, offre n. 2 camere triple (matrimoniale + letto singolo) e due doppie (letto matrimoniale o n. 2 letti singoli a richiesta. Sono camere dotate di bagno e di ogni comfort. L&rsquo;ospite può usufruire anche di aree comuni: un salotto con televisore Led 40 pollici e consolle studio, una cucina attrezzata, un balcone (quale area smoking). Il parcheggio è privato, proprio sotto casa.

La posizione è strategica per Ancona: a 10 minuti di auto dalla Riviera del Conero, a due passi dal centro città (fermata autobus a 10 metri) adiacente la Casa di Cura Villa Igea, vicino al Centro di Selezione della Marina Militare, alla sede centrale dell&rsquo;Istituto Caggiari, del Palaindoor e del campo di atletica leggera "Conti".',
             'importo' => '220',
             'dimensione' => '18',
             'tipologia' => 'Appartamento',
             'data_inizio_disponibilita' => date("2022-02-17"),
             'data_fine_disponibilita' => date("2023-03-17"),
             'servizi_inclusi' => 'Wi-fi,Parcheggio Riservato',
             'eta_minima' => '19',
             'genere_richiesto' => null,
             'assegnato' => '0',               
             'data_assegnazione' => null,
             'immagine' => '1.jpg',
             'numero_posti_letto_totali' => '10',
             'C_numero_posti_letto_in_camera' => null,
             'A_numero_camere' => '4',
             'A_locali_presenti' => 'Cucina',
             'created_at' => date("Y-m-d H:i:s"),
             'updated_at' => date("Y-m-d H:i:s")],
            
            ['AnnuncioId' => '6',
             'user_id' => '1',
             'citta' => 'Ancona',               
             'zona_quartiere' => 'Q2',
             'indirizzo' => 'via flavia 25',
             'descrizione' => 'camera spaziosa',
             'importo' => '220',
             'dimensione' => '18',
             'tipologia' => 'Posto Letto',
             'data_inizio_disponibilita' => date("2022-02-17"),
             'data_fine_disponibilita' => date("2023-03-17"),
             'servizi_inclusi' => 'lavastoviglie garage',
             'eta_minima' => '19',
             'genere_richiesto' => null,
             'assegnato' => '0',               
             'data_assegnazione' => null,
             'immagine' => '2.jpg',
             'numero_posti_letto_totali' => null,
             'C_numero_posti_letto_in_camera' => null,
             'A_numero_camere' => '1',
             'A_locali_presenti' => 'Cucina',
             'created_at' => date("Y-m-d H:i:s"),
             'updated_at' => date("Y-m-d H:i:s")],
            
            ['AnnuncioId' => '7',
            'user_id' => '1',
             'citta' => 'Ancona',               
             'zona_quartiere' => 'Q2',
             'indirizzo' => 'via flavia 25',
             'descrizione' => 'camera spaziosa',
             'importo' => '220',
             'dimensione' => '18',
             'tipologia' => 'Posto Letto',
             'data_inizio_disponibilita' => date("2022-02-17"),
             'data_fine_disponibilita' => date("2023-03-17"),
             'servizi_inclusi' => 'lavastoviglie garage',
             'eta_minima' => '19',
             'genere_richiesto' => null,
             'assegnato' => '0',               
             'data_assegnazione' => null,
             'immagine' => '3.jpg',
             'numero_posti_letto_totali' => null,
             'C_numero_posti_letto_in_camera' => null,
             'A_numero_camere' => '1',
             'A_locali_presenti' => 'Cucina',
             'created_at' => date("Y-m-d H:i:s"),
             'updated_at' => date("Y-m-d H:i:s")],
            
            ['AnnuncioId' => '8',
            'user_id' => '1',
             'citta' => 'Ancona',               
             'zona_quartiere' => 'Q2',
             'indirizzo' => 'via flavia 25',
             'descrizione' => 'camera spaziosa',
             'importo' => '220',
             'dimensione' => '18',
             'tipologia' => 'Posto Letto',
             'data_inizio_disponibilita' => date("2022-02-17"),
             'data_fine_disponibilita' => date("2023-03-17"),
             'servizi_inclusi' => 'lavastoviglie garage',
             'eta_minima' => '19',
             'genere_richiesto' => null,
             'assegnato' => '0',               
             'data_assegnazione' => null,
             'immagine' => '4.jpg',
             'numero_posti_letto_totali' => null,
             'C_numero_posti_letto_in_camera' => null,
             'A_numero_camere' => '1',
             'A_locali_presenti' => 'Cucina',
             'created_at' => date("Y-m-d H:i:s"),
             'updated_at' => date("Y-m-d H:i:s")],
            
            ['AnnuncioId' => '9',
             'user_id' => '1',
             'citta' => 'Ancona',               
             'zona_quartiere' => 'Q2',
             'indirizzo' => 'via flavia 25',
             'descrizione' => 'camera spaziosa',
             'importo' => '220',
             'dimensione' => '18',
             'tipologia' => 'Posto Letto',
             'data_inizio_disponibilita' => date("2022-02-17"),
             'data_fine_disponibilita' => date("2023-03-17"),
             'servizi_inclusi' => 'lavastoviglie garage',
             'eta_minima' => '19',
             'genere_richiesto' => null,
             'assegnato' => '0',               
             'data_assegnazione' => null,
             'immagine' => '5.jpg',
              'numero_posti_letto_totali' => null,
             'C_numero_posti_letto_in_camera' => null,
             'A_numero_camere' => '1',
             'A_locali_presenti' => 'Cucina',
             'created_at' => date("Y-m-d H:i:s"),
             'updated_at' => date("Y-m-d H:i:s")],
            
            ['AnnuncioId' => '10',
           'user_id' => '1',
             'citta' => 'Ancona',               
             'zona_quartiere' => 'Q2',
             'indirizzo' => 'via flavia 25',
             'descrizione' => 'camera spaziosa',
             'importo' => '220',
             'dimensione' => '18',
             'tipologia' => 'Posto Letto',
             'data_inizio_disponibilita' => date("2022-02-17"),
             'data_fine_disponibilita' => date("2023-03-17"),
             'servizi_inclusi' => 'lavastoviglie garage',
             'eta_minima' => '19',
             'genere_richiesto' => null,
             'assegnato' => '0',               
             'data_assegnazione' => null,
             'immagine' => '2.jpg',
             'numero_posti_letto_totali' => null,
             'C_numero_posti_letto_in_camera' => null,
             'A_numero_camere' => '1',
             'A_locali_presenti' => 'Cucina',
             'created_at' => date("Y-m-d H:i:s"),
             'updated_at' => date("Y-m-d H:i:s")],
            
            ['AnnuncioId' => '11',
             'user_id' => '1',
             'citta' => 'Ancona',               
             'zona_quartiere' => 'Q2',
             'indirizzo' => 'via flavia 25',
             'descrizione' => 'camera spaziosa',
             'importo' => '220',
             'dimensione' => '18',
             'tipologia' => 'Posto Letto',
             'data_inizio_disponibilita' => date("2022-02-17"),
             'data_fine_disponibilita' => date("2023-03-17"),
             'servizi_inclusi' => 'lavastoviglie garage',
             'eta_minima' => '19',
             'genere_richiesto' => null,
             'assegnato' => '0',               
             'data_assegnazione' => null,
             'immagine' => '1.jpg',
              'numero_posti_letto_totali' => null,
             'C_numero_posti_letto_in_camera' => null,
             'A_numero_camere' => '1',
             'A_locali_presenti' => 'Cucina',
             'created_at' => date("Y-m-d H:i:s"),
             'updated_at' => date("Y-m-d H:i:s")],
           
            
            ['AnnuncioId' => '12',
            'user_id' => '1',
             'citta' => 'Ancona',               
             'zona_quartiere' => 'Q2',
             'indirizzo' => 'via flavia 25',
             'descrizione' => 'camera spaziosa',
             'importo' => '220',
             'dimensione' => '18',
             'tipologia' => 'Posto Letto',
             'data_inizio_disponibilita' => date("2022-02-17"),
             'data_fine_disponibilita' => date("2023-03-17"),
             'servizi_inclusi' => 'lavastoviglie garage',
             'eta_minima' => '19',
             'genere_richiesto' => null,
             'assegnato' => '0',               
             'data_assegnazione' => null,
             'immagine' => '3.jpg',
              'numero_posti_letto_totali' => null,
             'C_numero_posti_letto_in_camera' => null,
             'A_numero_camere' => '1',
             'A_locali_presenti' => 'Cucina',
             'created_at' => date("Y-m-d H:i:s"),
             'updated_at' => date("Y-m-d H:i:s")],
            
        ]);

        DB::table('faq')->insert([
            ['FaqId' => '1',
             'domanda' => 'Come posso inserire un mio appartamento?',
             'risposta' => 'Per inserire un annuncio è sufficiente cliccare sulla voce "Crea annuncio"',               
             'created_at' => date("Y-m-d H:i:s"),
             'updated_at' => date("Y-m-d H:i:s")],
            
            ['FaqId' => '2',
             'domanda' => 'Come faccio ad opzionare un offerta?',
             'risposta' => 'Per opzionare un offerta desiderata è necessario registrarsi come locatario/studente ed accedere nella scheda alloggio desiderata ed infine cliccare il pulsante "opziona offerta" ',               
             'created_at' => date("Y-m-d H:i:s"),
             'updated_at' => date("Y-m-d H:i:s")],
            
            ['FaqId' => '3',
             'domanda' => 'Come faccio a filtrare le offerte?',
             'risposta' => 'Registrandosi come loatario/studente si accede alla funzionalità di filtraggio',               
             'created_at' => date("Y-m-d H:i:s"),
             'updated_at' => date("Y-m-d H:i:s")],
            
            ['FaqId' => '4',
             'domanda' => 'Chi siete?',
             'risposta' => 'Renthem',               
             'created_at' => date("Y-m-d H:i:s"),
             'updated_at' => date("Y-m-d H:i:s")],
        ]);
        
        DB::table('messaggi')->insert([
            ['id' => '1',
             'idlocatario' => '2',
             'idlocatore' => '1', 
             'contenuto' => 'Salve vorrei sapere di più sull annuncio', 
             'sender' => '0', 
             'created_at' => date("Y-m-d H:i:s"),
             'updated_at' => date("Y-m-d H:i:s")],
            
            ['id' => '2',
             'idlocatario' => '2',
             'idlocatore' => '1', 
             'contenuto' => 'Salve, che cosa desidera sapere in particolare?', 
             'sender' => '1', 
             'created_at' => date("Y-m-d H:i:s"),
             'updated_at' => date("Y-m-d H:i:s")],
            
            ['id' => '3',
             'idlocatario' => '2',
             'idlocatore' => '1', 
             'contenuto' => 'è possibile tenere animali? ', 
             'sender' => '0', 
             'created_at' => date("Y-m-d H:i:s"),
             'updated_at' => date("Y-m-d H:i:s")],
            
            ['id' => '4',
             'idlocatario' => '2',
             'idlocatore' => '1', 
             'contenuto' => 'Si certamente', 
             'sender' => '1', 
             'created_at' => date("Y-m-d H:i:s"),
             'updated_at' => date("Y-m-d H:i:s")],
        ]);
    }

}
