<?php

use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder {

    /**
     * Seed the application's database.
     *
     * @return void
     */

    public function run() {
        
        DB::table('users')->insert([
            [
             'nome' => 'lore',
             'cognome' => 'lore',               
             'data_nascita' => date("Y-m-d"),
             'genere' => 'maschio',
             'email' => 'lore@lore.it',
             'telefono' => '3980901389',
             'username' => 'lorelore',
             'password' => Hash::make('Njpwskf4'),
             'role' => 'locatore',
             'created_at' => date("Y-m-d H:i:s"),
             'updated_at' => date("Y-m-d H:i:s")],
            
            [
             'nome' => 'lario',
             'cognome' => 'lario',               
             'data_nascita' => date("Y-m-d"),
             'genere' => 'maschio',
             'email' => 'lario@lario.it',
             'telefono' => '3182201389',
             'username' => 'lariolario',
             'password' => Hash::make('Njpwskf4'),
             'role' => 'locatario',
             'created_at' => date("Y-m-d H:i:s"),
             'updated_at' => date("Y-m-d H:i:s")],
            
            [
             'nome' => 'admin',
             'cognome' => 'admin',               
             'data_nascita' => date("Y-m-d"),
             'genere' => 'maschio',
             'email' => 'admin@admin.it',
             'telefono' => '3280912439',
             'username' => 'adminadmin',
             'password' => Hash::make('Njpwskf4'),
             'role' => 'admin',
             'created_at' => date("Y-m-d H:i:s"),
             'updated_at' => date("Y-m-d H:i:s")],
            
            [
             'nome' => 'mario',
             'cognome' => 'mario',               
             'data_nascita' => date("Y-m-d"),
             'genere' => 'maschio',
             'email' => 'lario@lario.it',
             'telefono' => '3182201389',
             'username' => 'mariomario',
             'password' => Hash::make('mariomario'),
             'role' => 'locatario',
             'created_at' => date("Y-m-d H:i:s"),
             'updated_at' => date("Y-m-d H:i:s")],
            
            [
             'nome' => 'catore',
             'cognome' => 'catore',               
             'data_nascita' => date("Y-m-d"),
             'genere' => 'maschio',
             'email' => 'catore@catore.it',
             'telefono' => '3182201389',
             'username' => 'catore',
             'password' => Hash::make('catore'),
             'role' => 'locatore',
             'created_at' => date("Y-m-d H:i:s"),
             'updated_at' => date("Y-m-d H:i:s")],
            
            [
             'nome' => 'min',
             'cognome' => 'admin',               
             'data_nascita' => date("Y-m-d"),
             'genere' => 'maschio',
             'email' => 'lario@lario.it',
             'telefono' => '3182201389',
             'username' => 'minmin',
             'password' => Hash::make('minmin'),
             'role' => 'admin',
             'created_at' => date("Y-m-d H:i:s"),
             'updated_at' => date("Y-m-d H:i:s")],
        ]);

        DB::table('annunci')->insert([
            ['AnnuncioId' => '1',
             'user_id' => '1',
             'citta' => 'Ancona',               
             'zona_quartiere' => 'Semicentro',
             'indirizzo' => 'via brecce bianche 12',
             'descrizione' => "L’appartamento, di recente realizzazione, ha un ingresso con cucina, divano ed angolo tv, un bagno ed una camera.
Ha a disposizione un giardino di proprietà comunicante con un piccolo parco comunale.",
             'importo' => '750',
             'dimensione' => '70',
             'tipologia' => 'Appartamento',
             'data_inizio_disponibilita' => date("2021-09-15"),
             'data_fine_disponibilita' => date("2022-09-15"),
             'servizi_inclusi' => 'Wi-fi,Parcheggio Riservato',
             'eta_minima' => '19',
             'genere_richiesto' => 'uomini',
             'assegnato' => '0',               
             'data_assegnazione' => null,
             'immagine' => '1.jpg',
             'numero_posti_letto_totali' => 5,
             'C_numero_posti_letto_in_camera' => null,
             'A_numero_camere' => '3',
             'A_locali_presenti' => 'Cucina,Bagno Doppio,Garage',
             'created_at' => date("2021-09-01 12:30:00"),
             'updated_at' => date("Y-m-d H:i:s")],
            
            ['AnnuncioId' => '2',
             'user_id' => '5',
             'citta' => 'Ancona',               
             'zona_quartiere' => 'Semicentro',
             'indirizzo' => 'via flavia 25',
             'descrizione' => ' Il B&B offre quattro camere con bagno privato e Wi-Fi illimitato.
Gli spazi sono stati interamente ristrutturati nel 2020 per garantire ai propri ospiti il massimo del comfort e un piacevole soggiorno ad Ancona. Contattaci per maggiori informazioni.',
             'importo' => '220',
             'dimensione' => '20',
             'tipologia' => 'Posto Letto',
             'data_inizio_disponibilita' => date("2022-02-17"),
             'data_fine_disponibilita' => date("2023-02-17"),
             'servizi_inclusi' => 'Angolo Studio,minibar,Wi-fi',
             'eta_minima' => '19',
             'genere_richiesto' => null,
             'assegnato' => '1',               
             'data_assegnazione' => date("2022-05-31"),
             'immagine' => '2.jpg',
             'numero_posti_letto_totali' => 6,
             'C_numero_posti_letto_in_camera' => 2,
             'A_numero_camere' => null,
             'A_locali_presenti' => null,
             'created_at' => date("2022-02-01 10:00:00"),
             'updated_at' => date("Y-m-d H:i:s")],
            
            ['AnnuncioId' => '3',
            'user_id' => '5',
             'citta' => 'Jesi',               
             'zona_quartiere' => 'Centro',
             'indirizzo' => 'viale della vittoria 25',
             'descrizione' => "Il B&B è situato al piano terra di un piccolo condominio a due passi dal centro storico della città, vicino l'ospedale, in una zona residenziale che presenta facilità di parcheggio, servizi (banca, farmacia, supermercato) e collegamenti.
              Il B&B dispone di un ingresso indipendente, una cucina soggiorno dove viene servita la colazione, una camera doppia e una tripla (anche ad uso singola), ognuna con bagno privato in stanza e internet gratuito e illimitato, termo autonomo, TV, asciugacapelli; sono accettati animali.
",
             'importo' => '300',
             'dimensione' => '20',
             'tipologia' => 'Posto Letto',
             'data_inizio_disponibilita' => date("2022-01-17"),
             'data_fine_disponibilita' => date("2023-01-17"),
             'servizi_inclusi' => 'Bagno Singolo,Wi-fi ',
             'eta_minima' => '19',
             'genere_richiesto' => 'donne',
             'assegnato' => '0',               
             'data_assegnazione' => null,
             'immagine' => '3.jpg',
              'numero_posti_letto_totali' => 5,
             'C_numero_posti_letto_in_camera' => 2,
             'A_numero_camere' => null,
             'A_locali_presenti' => null,
             'created_at' => date("2022-01-17 13:00:00"),
             'updated_at' => date("Y-m-d H:i:s")],
            
            
            ['AnnuncioId' => '4',
             'user_id' => '1',
             'citta' => 'Ancona',               
             'zona_quartiere' => 'Periferia',
             'indirizzo' => 'Via Direttissima del Conero, 1/3',
             'descrizione' => 'camera spaziosa',
             'importo' => '220',
             'dimensione' => '18',
             'tipologia' => 'Appartamento',
             'data_inizio_disponibilita' => date("2021-11-15"),
             'data_fine_disponibilita' => date("2022-11-15"),
             'servizi_inclusi' => 'lavastoviglie garage',
             'eta_minima' => '19',
             'genere_richiesto' => null,
             'assegnato' => '0',               
             'data_assegnazione' => null,
             'immagine' => '4.jpg',
             'numero_posti_letto_totali' => null,
             'C_numero_posti_letto_in_camera' => null,
             'A_numero_camere' => '1',
             'A_locali_presenti' => 'Cucina',
             'created_at' => date("2021-11-15 H:i:s"),
             'updated_at' => date("Y-m-d H:i:s")],
            
            ['AnnuncioId' => '5',
           'user_id' => '5',
             'citta' => 'Ancona',               
             'zona_quartiere' => 'Semicentro',
             'indirizzo' => 'via maggini 18',
             'descrizione' => 'Questa nuova struttura ricettiva, dalle linee sobrie ed essenziali, offre n. 2 camere triple (matrimoniale + letto singolo) e due doppie (letto matrimoniale o n. 2 letti singoli a richiesta. Sono camere dotate di bagno e di ogni comfort. L&rsquo;ospite può usufruire anche di aree comuni: un salotto con televisore Led 40 pollici e consolle studio, una cucina attrezzata, un balcone (quale area smoking).\n Il parcheggio è privato, proprio sotto casa.

La posizione è strategica per Ancona: a 10 minuti di auto dalla Riviera del Conero, a due passi dal centro città (fermata autobus a 10 metri) adiacente la Casa di Cura Villa Igea, vicino al Centro di Selezione della Marina Militare, alla sede centrale dell&rsquo;Istituto Caggiari, del Palaindoor e del campo di atletica leggera "Conti".',
             'importo' => '220',
             'dimensione' => '18',
             'tipologia' => 'Appartamento',
             'data_inizio_disponibilita' => date("2022-02-17"),
             'data_fine_disponibilita' => date("2023-03-17"),
             'servizi_inclusi' => 'Wi-fi,Parcheggio Riservato',
             'eta_minima' => '19',
             'genere_richiesto' => null,
             'assegnato' => '0',               
             'data_assegnazione' => null,
             'immagine' => '1.jpg',
             'numero_posti_letto_totali' => '10',
             'C_numero_posti_letto_in_camera' => null,
             'A_numero_camere' => '4',
             'A_locali_presenti' => 'Cucina',
             'created_at' => date("Y-m-d H:i:s"),
             'updated_at' => date("Y-m-d H:i:s")],
            
            ['AnnuncioId' => '6',
             'user_id' => '1',
             'citta' => 'Ancona',               
             'zona_quartiere' => 'Q2',
             'indirizzo' => 'via flavia 25',
             'descrizione' => 'camera spaziosa',
             'importo' => '220',
             'dimensione' => '18',
             'tipologia' => 'Posto Letto',
             'data_inizio_disponibilita' => date("2022-02-17"),
             'data_fine_disponibilita' => date("2023-03-17"),
             'servizi_inclusi' => 'lavastoviglie garage',
             'eta_minima' => '19',
             'genere_richiesto' => null,
             'assegnato' => '0',               
             'data_assegnazione' => null,
             'immagine' => '2.jpg',
             'numero_posti_letto_totali' => null,
             'C_numero_posti_letto_in_camera' => null,
             'A_numero_camere' => '1',
             'A_locali_presenti' => 'Cucina',
             'created_at' => date("Y-m-d H:i:s"),
             'updated_at' => date("Y-m-d H:i:s")],
            
            ['AnnuncioId' => '7',
            'user_id' => '1',
             'citta' => 'Ancona',               
             'zona_quartiere' => 'Q2',
             'indirizzo' => 'via flavia 25',
             'descrizione' => 'camera spaziosa',
             'importo' => '220',
             'dimensione' => '18',
             'tipologia' => 'Posto Letto',
             'data_inizio_disponibilita' => date("2022-02-17"),
             'data_fine_disponibilita' => date("2023-03-17"),
             'servizi_inclusi' => 'lavastoviglie garage',
             'eta_minima' => '19',
             'genere_richiesto' => null,
             'assegnato' => '0',               
             'data_assegnazione' => null,
             'immagine' => '3.jpg',
             'numero_posti_letto_totali' => null,
             'C_numero_posti_letto_in_camera' => null,
             'A_numero_camere' => '1',
             'A_locali_presenti' => 'Cucina',
             'created_at' => date("Y-m-d H:i:s"),
             'updated_at' => date("Y-m-d H:i:s")],
            
            ['AnnuncioId' => '8',
            'user_id' => '1',
             'citta' => 'Ancona',               
             'zona_quartiere' => 'Q2',
             'indirizzo' => 'via flavia 25',
             'descrizione' => 'camera spaziosa',
             'importo' => '220',
             'dimensione' => '18',
             'tipologia' => 'Posto Letto',
             'data_inizio_disponibilita' => date("2022-02-17"),
             'data_fine_disponibilita' => date("2023-03-17"),
             'servizi_inclusi' => 'lavastoviglie garage',
             'eta_minima' => '19',
             'genere_richiesto' => null,
             'assegnato' => '0',               
             'data_assegnazione' => null,
             'immagine' => '4.jpg',
             'numero_posti_letto_totali' => null,
             'C_numero_posti_letto_in_camera' => null,
             'A_numero_camere' => '1',
             'A_locali_presenti' => 'Cucina',
             'created_at' => date("Y-m-d H:i:s"),
             'updated_at' => date("Y-m-d H:i:s")],
            
            ['AnnuncioId' => '9',
             'user_id' => '1',
             'citta' => 'Ancona',               
             'zona_quartiere' => 'Q2',
             'indirizzo' => 'via flavia 25',
             'descrizione' => 'camera spaziosa',
             'importo' => '220',
             'dimensione' => '18',
             'tipologia' => 'Posto Letto',
             'data_inizio_disponibilita' => date("2022-02-17"),
             'data_fine_disponibilita' => date("2023-03-17"),
             'servizi_inclusi' => 'lavastoviglie garage',
             'eta_minima' => '19',
             'genere_richiesto' => null,
             'assegnato' => '0',               
             'data_assegnazione' => null,
             'immagine' => '5.jpg',
              'numero_posti_letto_totali' => null,
             'C_numero_posti_letto_in_camera' => null,
             'A_numero_camere' => '1',
             'A_locali_presenti' => 'Cucina',
             'created_at' => date("Y-m-d H:i:s"),
             'updated_at' => date("Y-m-d H:i:s")],
            
            ['AnnuncioId' => '10',
           'user_id' => '1',
             'citta' => 'Ancona',               
             'zona_quartiere' => 'Q2',
             'indirizzo' => 'via flavia 25',
             'descrizione' => 'camera spaziosa',
             'importo' => '220',
             'dimensione' => '18',
             'tipologia' => 'Posto Letto',
             'data_inizio_disponibilita' => date("2022-02-17"),
             'data_fine_disponibilita' => date("2023-03-17"),
             'servizi_inclusi' => 'lavastoviglie garage',
             'eta_minima' => '19',
             'genere_richiesto' => null,
             'assegnato' => '0',               
             'data_assegnazione' => null,
             'immagine' => '2.jpg',
             'numero_posti_letto_totali' => null,
             'C_numero_posti_letto_in_camera' => null,
             'A_numero_camere' => '1',
             'A_locali_presenti' => 'Cucina',
             'created_at' => date("Y-m-d H:i:s"),
             'updated_at' => date("Y-m-d H:i:s")],
            
            ['AnnuncioId' => '11',
             'user_id' => '1',
             'citta' => 'Ancona',               
             'zona_quartiere' => 'Q2',
             'indirizzo' => 'via flavia 25',
             'descrizione' => 'camera spaziosa',
             'importo' => '220',
             'dimensione' => '18',
             'tipologia' => 'Posto Letto',
             'data_inizio_disponibilita' => date("2022-02-17"),
             'data_fine_disponibilita' => date("2023-03-17"),
             'servizi_inclusi' => 'lavastoviglie garage',
             'eta_minima' => '19',
             'genere_richiesto' => null,
             'assegnato' => '0',               
             'data_assegnazione' => null,
             'immagine' => '1.jpg',
              'numero_posti_letto_totali' => null,
             'C_numero_posti_letto_in_camera' => null,
             'A_numero_camere' => '1',
             'A_locali_presenti' => 'Cucina',
             'created_at' => date("Y-m-d H:i:s"),
             'updated_at' => date("Y-m-d H:i:s")],
           
            
            ['AnnuncioId' => '12',
            'user_id' => '1',
             'citta' => 'Ancona',               
             'zona_quartiere' => 'Q2',
             'indirizzo' => 'via flavia 25',
             'descrizione' => 'camera spaziosa',
             'importo' => '220',
             'dimensione' => '18',
             'tipologia' => 'Posto Letto',
             'data_inizio_disponibilita' => date("2022-02-17"),
             'data_fine_disponibilita' => date("2023-03-17"),
             'servizi_inclusi' => 'lavastoviglie garage',
             'eta_minima' => '19',
             'genere_richiesto' => null,
             'assegnato' => '0',               
             'data_assegnazione' => null,
             'immagine' => '3.jpg',
              'numero_posti_letto_totali' => null,
             'C_numero_posti_letto_in_camera' => null,
             'A_numero_camere' => '1',
             'A_locali_presenti' => 'Cucina',
             'created_at' => date("Y-m-d H:i:s"),
             'updated_at' => date("Y-m-d H:i:s")],
            
        ]);

        DB::table('faq')->insert([
            ['FaqId' => '1',
             'domanda' => 'Come posso inserire un mio appartamento?',
             'risposta' => 'Per inserire un annuncio è sufficiente cliccare sulla voce "Crea annuncio"',               
             'created_at' => date("Y-m-d H:i:s"),
             'updated_at' => date("Y-m-d H:i:s")],
            
            ['FaqId' => '2',
             'domanda' => 'Come faccio ad opzionare un offerta?',
             'risposta' => 'Per opzionare un offerta desiderata è necessario registrarsi come locatario/studente ed accedere nella scheda alloggio desiderata ed infine cliccare il pulsante "opziona offerta" ',               
             'created_at' => date("Y-m-d H:i:s"),
             'updated_at' => date("Y-m-d H:i:s")],
            
            ['FaqId' => '3',
             'domanda' => 'Come faccio a filtrare le offerte?',
             'risposta' => 'Registrandosi come loatario/studente si accede alla funzionalità di filtraggio',               
             'created_at' => date("Y-m-d H:i:s"),
             'updated_at' => date("Y-m-d H:i:s")],
            
            ['FaqId' => '4',
             'domanda' => 'Chi siete?',
             'risposta' => 'Renthem',               
             'created_at' => date("Y-m-d H:i:s"),
             'updated_at' => date("Y-m-d H:i:s")],
        ]);
        
        DB::table('messaggi')->insert([
            ['id' => '1',
             'idlocatario' => '2',
             'idlocatore' => '1', 
             'contenuto' => "Salve, vorrei sapere di più sull'annuncio", 
             'sender' => '0', 
             'created_at' => date("Y-m-d H:i:s"),
             'updated_at' => date("Y-m-d H:i:s")],
            
            ['id' => '2',
             'idlocatario' => '2',
             'idlocatore' => '1', 
             'contenuto' => 'Salve, che cosa desidera sapere in particolare?', 
             'sender' => '1', 
             'created_at' => date("Y-m-d H:i:s"),
             'updated_at' => date("Y-m-d H:i:s")],
            
            ['id' => '3',
             'idlocatario' => '2',
             'idlocatore' => '1', 
             'contenuto' => "E' possibile tenere animali? ", 
             'sender' => '0', 
             'created_at' => date("Y-m-d H:i:s"),
             'updated_at' => date("Y-m-d H:i:s")],
            
            ['id' => '4',
             'idlocatario' => '2',
             'idlocatore' => '1', 
             'contenuto' => 'Si certamente', 
             'sender' => '1', 
             'created_at' => date("Y-m-d H:i:s"),
             'updated_at' => date("Y-m-d H:i:s")],
            
            ['id' => '5',
             'idlocatario' => '2',
             'idlocatore' => '1', 
             'contenuto' => "L'utente lario lario ha opzionato il seguente Appartamento, in via brecce bianche 12 Ancona.", 
             'sender' => '0', 
             'created_at' => date("Y-m-d H:i:s"),
             'updated_at' => date("Y-m-d H:i:s")],
            
            ['id' => '6',
             'idlocatario' => '2',
             'idlocatore' => '5', 
             'contenuto' => "L'utente lario lario ha opzionato il seguente Posto Letto, in viale della vittoria 25 Jesi.", 
             'sender' => '0', 
             'created_at' => date("Y-m-d H:i:s"),
             'updated_at' => date("Y-m-d H:i:s")],
            
            ['id' => '7',
             'idlocatario' => '4',
             'idlocatore' => '5', 
             'contenuto' => "L'utente catore catore ha opzionato il seguente Posto Letto, in  via flavia 25 Ancona.", 
             'sender' => '0', 
             'created_at' => date("Y-m-d H:i:s"),
             'updated_at' => date("Y-m-d H:i:s")],
            
            ['id' => '8',
             'idlocatario' => '4',
             'idlocatore' => '5', 
             'contenuto' => "L'utente catore catore ha opzionato il seguente Posto Letto, in viale della vittoria 25 Jesi.", 
             'sender' => '0', 
             'created_at' => date("Y-m-d H:i:s"),
             'updated_at' => date("Y-m-d H:i:s")],
        ]);
        
         DB::table('annunci_users')->insert([
            ['id' => '1',
             'user_id' => 2,
             'annuncio_AnnuncioId' => 1,    
             'assegnato' => false,   
             'created_at' => date("Y-m-d H:i:s"),
             'updated_at' => date("Y-m-d H:i:s")],
             
             ['id' => '2',
             'user_id' => 2,
             'annuncio_AnnuncioId' => 3,    
             'assegnato' => false,   
             'created_at' => date("Y-m-d H:i:s"),
             'updated_at' => date("Y-m-d H:i:s")],
             
             ['id' => '3',
             'user_id' => 4,
             'annuncio_AnnuncioId' => 3,    
             'assegnato' => false,   
             'created_at' => date("Y-m-d H:i:s"),
             'updated_at' => date("Y-m-d H:i:s")],
             
              ['id' => '4',
             'user_id' => 4,
             'annuncio_AnnuncioId' => 2,    
             'assegnato' => true,   
             'created_at' => date("Y-m-d H:i:s"),
             'updated_at' => date("Y-m-d H:i:s")],
             
             
        ]);     
    }

}
