<?php

use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder {

    /**
     * Seed the application's database.
     *
     * @return void
     */

    public function run() {
        
        DB::table('users')->insert([
            [
             'nome' => 'lore',
             'cognome' => 'lore',               
             'data_nascita' => date("Y-m-d"),
             'genere' => 'maschio',
             'email' => 'lore@lore.it',
             'telefono' => '3980901389',
             'username' => 'lorelore',
             'password' => Hash::make('Njpwskf4'),
             'role' => 'locatore',
             'created_at' => date("Y-m-d H:i:s"),
             'updated_at' => date("Y-m-d H:i:s")],
            
            [
             'nome' => 'lario',
             'cognome' => 'lario',               
             'data_nascita' => date("Y-m-d"),
             'genere' => 'maschio',
             'email' => 'lario@lario.it',
             'telefono' => '3182201389',
             'username' => 'lariolario',
             'password' => Hash::make('Njpwskf4'),
             'role' => 'locatario',
             'created_at' => date("Y-m-d H:i:s"),
             'updated_at' => date("Y-m-d H:i:s")],
            
            [
             'nome' => 'admin',
             'cognome' => 'admin',               
             'data_nascita' => date("Y-m-d"),
             'genere' => 'maschio',
             'email' => 'admin@admin.it',
             'telefono' => '3280912439',
             'username' => 'adminadmin',
             'password' => Hash::make('Njpwskf4'),
             'role' => 'admin',
             'created_at' => date("Y-m-d H:i:s"),
             'updated_at' => date("Y-m-d H:i:s")],
            
            [
             'nome' => 'mario',
             'cognome' => 'mario',               
             'data_nascita' => date("Y-m-d"),
             'genere' => 'maschio',
             'email' => 'lario@lario.it',
             'telefono' => '3182201389',
             'username' => 'mariomario',
             'password' => Hash::make('mariomario'),
             'role' => 'locatario',
             'created_at' => date("Y-m-d H:i:s"),
             'updated_at' => date("Y-m-d H:i:s")],
            
            [
             'nome' => 'catore',
             'cognome' => 'catore',               
             'data_nascita' => date("Y-m-d"),
             'genere' => 'maschio',
             'email' => 'lario@lario.it',
             'telefono' => '3182201389',
             'username' => 'catore',
             'password' => Hash::make('catore'),
             'role' => 'locatore',
             'created_at' => date("Y-m-d H:i:s"),
             'updated_at' => date("Y-m-d H:i:s")],
            
            [
             'nome' => 'min',
             'cognome' => 'admin',               
             'data_nascita' => date("Y-m-d"),
             'genere' => 'maschio',
             'email' => 'lario@lario.it',
             'telefono' => '3182201389',
             'username' => 'minmin',
             'password' => Hash::make('minmin'),
             'role' => 'admin',
             'created_at' => date("Y-m-d H:i:s"),
             'updated_at' => date("Y-m-d H:i:s")],
        ]);

        DB::table('annunci')->insert([
            ['AnnuncioId' => '1',
             'user_id' => '1',
             'citta' => 'Ancona',               
             'zona_quartiere' => 'Q1',
             'indirizzo' => 'via brecce bianche 12',
             'descrizione' => 'appartamento',
             'importo' => '750',
             'dimensione' => '70',
             'tipologia' => 'Appartamento',
             'data_inizio_disponibilita' => date("2022-05-15"),
             'data_fine_disponibilita' => date("2023-06-15"),
             'servizi_inclusi' => 'lavastoviglie garage',
             'eta_minima' => '19',
             'genere_richiesto' => 'uomini',
             'assegnato' => '0',               
             'data_assegnazione' => null,
             'immagine' => '1.jpg',
             'C_numero_posti_letto_totali' => null,
             'C_numero_posti_letto_in_camera' => null,
             'C_presenza_angolo_studio' => null,
             'A_numero_camere' => '1',
             'A_numero_posti_letto' => '1',
             'A_presenza_cucina' => '1',
             'A_presenza_locale_ricreativo' => '1',
             'A_servizi_disponibili' => 'parcheggio',
             'created_at' => date("Y-m-d H:i:s"),
             'updated_at' => date("Y-m-d H:i:s")],
            
            ['AnnuncioId' => '2',
             'user_id' => '1',
             'citta' => 'Ancona',               
             'zona_quartiere' => 'Q2',
             'indirizzo' => 'via flavia 25',
             'descrizione' => 'camera spaziosa',
             'importo' => '220',
             'dimensione' => '18',
             'tipologia' => 'Posto Letto',
             'data_inizio_disponibilita' => date("2022-02-17"),
             'data_fine_disponibilita' => date("2023-03-17"),
             'servizi_inclusi' => 'lavastoviglie garage',
             'eta_minima' => '19',
             'genere_richiesto' => null,
             'assegnato' => '0',               
             'data_assegnazione' => null,
             'immagine' => '2.jpg',
             'C_numero_posti_letto_totali' => '1',
             'C_numero_posti_letto_in_camera' => '1',
             'C_presenza_angolo_studio' => '1',
             'A_numero_camere' => null,
             'A_numero_posti_letto' => null,
             'A_presenza_cucina' => null,
             'A_presenza_locale_ricreativo' => null,
             'A_servizi_disponibili' => 'parcheggio',
             'created_at' => date("Y-m-d H:i:s"),
             'updated_at' => date("Y-m-d H:i:s")],
            
            ['AnnuncioId' => '3',
            'user_id' => '1',
             'citta' => 'Ancona',               
             'zona_quartiere' => 'Q2',
             'indirizzo' => 'via flavia 25',
             'descrizione' => 'camera spaziosa',
             'importo' => '220',
             'dimensione' => '18',
             'tipologia' => 'Posto Letto',
             'data_inizio_disponibilita' => date("2022-02-17"),
             'data_fine_disponibilita' => date("2023-03-17"),
             'servizi_inclusi' => 'lavastoviglie garage',
             'eta_minima' => '19',
             'genere_richiesto' => null,
             'assegnato' => '0',               
             'data_assegnazione' => null,
             'immagine' => '3.jpg',
             'C_numero_posti_letto_totali' => '1',
             'C_numero_posti_letto_in_camera' => '1',
             'C_presenza_angolo_studio' => '1',
             'A_numero_camere' => null,
             'A_numero_posti_letto' => null,
             'A_presenza_cucina' => null,
             'A_presenza_locale_ricreativo' => null,
             'A_servizi_disponibili' => 'parcheggio',
             'created_at' => date("Y-m-d H:i:s"),
             'updated_at' => date("Y-m-d H:i:s")],
            
            
            ['AnnuncioId' => '4',
             'user_id' => '1',
             'citta' => 'Ancona',               
             'zona_quartiere' => 'Q2',
             'indirizzo' => 'via flavia 25',
             'descrizione' => 'camera spaziosa',
             'importo' => '220',
             'dimensione' => '18',
             'tipologia' => 'Posto Letto',
             'data_inizio_disponibilita' => date("2022-02-17"),
             'data_fine_disponibilita' => date("2023-03-17"),
             'servizi_inclusi' => 'lavastoviglie garage',
             'eta_minima' => '19',
             'genere_richiesto' => null,
             'assegnato' => '0',               
             'data_assegnazione' => null,
             'immagine' => '4.jpg',
             'C_numero_posti_letto_totali' => '1',
             'C_numero_posti_letto_in_camera' => '1',
             'C_presenza_angolo_studio' => '1',
             'A_numero_camere' => null,
             'A_numero_posti_letto' => null,
             'A_presenza_cucina' => null,
             'A_presenza_locale_ricreativo' => null,
             'A_servizi_disponibili' => 'parcheggio',
             'created_at' => date("Y-m-d H:i:s"),
             'updated_at' => date("Y-m-d H:i:s")],
            
            ['AnnuncioId' => '5',
           'user_id' => '1',
             'citta' => 'Ancona',               
             'zona_quartiere' => 'Q2',
             'indirizzo' => 'via flavia 25',
             'descrizione' => 'camera spaziosa',
             'importo' => '220',
             'dimensione' => '18',
             'tipologia' => 'Posto Letto',
             'data_inizio_disponibilita' => date("2022-02-17"),
             'data_fine_disponibilita' => date("2023-03-17"),
             'servizi_inclusi' => 'lavastoviglie garage',
             'eta_minima' => '19',
             'genere_richiesto' => null,
             'assegnato' => '0',               
             'data_assegnazione' => null,
             'immagine' => '1.jpg',
             'C_numero_posti_letto_totali' => '1',
             'C_numero_posti_letto_in_camera' => '1',
             'C_presenza_angolo_studio' => '1',
             'A_numero_camere' => null,
             'A_numero_posti_letto' => null,
             'A_presenza_cucina' => null,
             'A_presenza_locale_ricreativo' => null,
             'A_servizi_disponibili' => 'parcheggio',
             'created_at' => date("Y-m-d H:i:s"),
             'updated_at' => date("Y-m-d H:i:s")],
            
            ['AnnuncioId' => '6',
             'user_id' => '1',
             'citta' => 'Ancona',               
             'zona_quartiere' => 'Q2',
             'indirizzo' => 'via flavia 25',
             'descrizione' => 'camera spaziosa',
             'importo' => '220',
             'dimensione' => '18',
             'tipologia' => 'Posto Letto',
             'data_inizio_disponibilita' => date("2022-02-17"),
             'data_fine_disponibilita' => date("2023-03-17"),
             'servizi_inclusi' => 'lavastoviglie garage',
             'eta_minima' => '19',
             'genere_richiesto' => null,
             'assegnato' => '0',               
             'data_assegnazione' => null,
             'immagine' => '2.jpg',
             'C_numero_posti_letto_totali' => '1',
             'C_numero_posti_letto_in_camera' => '1',
             'C_presenza_angolo_studio' => '1',
             'A_numero_camere' => null,
             'A_numero_posti_letto' => null,
             'A_presenza_cucina' => null,
             'A_presenza_locale_ricreativo' => null,
             'A_servizi_disponibili' => 'parcheggio',
             'created_at' => date("Y-m-d H:i:s"),
             'updated_at' => date("Y-m-d H:i:s")],
            
            ['AnnuncioId' => '7',
            'user_id' => '1',
             'citta' => 'Ancona',               
             'zona_quartiere' => 'Q2',
             'indirizzo' => 'via flavia 25',
             'descrizione' => 'camera spaziosa',
             'importo' => '220',
             'dimensione' => '18',
             'tipologia' => 'Posto Letto',
             'data_inizio_disponibilita' => date("2022-02-17"),
             'data_fine_disponibilita' => date("2023-03-17"),
             'servizi_inclusi' => 'lavastoviglie garage',
             'eta_minima' => '19',
             'genere_richiesto' => null,
             'assegnato' => '0',               
             'data_assegnazione' => null,
             'immagine' => '3.jpg',
             'C_numero_posti_letto_totali' => '1',
             'C_numero_posti_letto_in_camera' => '1',
             'C_presenza_angolo_studio' => '1',
             'A_numero_camere' => null,
             'A_numero_posti_letto' => null,
             'A_presenza_cucina' => null,
             'A_presenza_locale_ricreativo' => null,
             'A_servizi_disponibili' => 'parcheggio',
             'created_at' => date("Y-m-d H:i:s"),
             'updated_at' => date("Y-m-d H:i:s")],
            
            ['AnnuncioId' => '8',
            'user_id' => '1',
             'citta' => 'Ancona',               
             'zona_quartiere' => 'Q2',
             'indirizzo' => 'via flavia 25',
             'descrizione' => 'camera spaziosa',
             'importo' => '220',
             'dimensione' => '18',
             'tipologia' => 'Posto Letto',
             'data_inizio_disponibilita' => date("2022-02-17"),
             'data_fine_disponibilita' => date("2023-03-17"),
             'servizi_inclusi' => 'lavastoviglie garage',
             'eta_minima' => '19',
             'genere_richiesto' => null,
             'assegnato' => '0',               
             'data_assegnazione' => null,
             'immagine' => '4.jpg',
             'C_numero_posti_letto_totali' => '1',
             'C_numero_posti_letto_in_camera' => '1',
             'C_presenza_angolo_studio' => '1',
             'A_numero_camere' => null,
             'A_numero_posti_letto' => null,
             'A_presenza_cucina' => null,
             'A_presenza_locale_ricreativo' => null,
             'A_servizi_disponibili' => 'parcheggio',
             'created_at' => date("Y-m-d H:i:s"),
             'updated_at' => date("Y-m-d H:i:s")],
            
            ['AnnuncioId' => '9',
             'user_id' => '1',
             'citta' => 'Ancona',               
             'zona_quartiere' => 'Q2',
             'indirizzo' => 'via flavia 25',
             'descrizione' => 'camera spaziosa',
             'importo' => '220',
             'dimensione' => '18',
             'tipologia' => 'Posto Letto',
             'data_inizio_disponibilita' => date("2022-02-17"),
             'data_fine_disponibilita' => date("2023-03-17"),
             'servizi_inclusi' => 'lavastoviglie garage',
             'eta_minima' => '19',
             'genere_richiesto' => null,
             'assegnato' => '0',               
             'data_assegnazione' => null,
             'immagine' => '5.jpg',
             'C_numero_posti_letto_totali' => '1',
             'C_numero_posti_letto_in_camera' => '1',
             'C_presenza_angolo_studio' => '1',
             'A_numero_camere' => null,
             'A_numero_posti_letto' => null,
             'A_presenza_cucina' => null,
             'A_presenza_locale_ricreativo' => null,
             'A_servizi_disponibili' => 'parcheggio',
             'created_at' => date("Y-m-d H:i:s"),
             'updated_at' => date("Y-m-d H:i:s")],
            
            ['AnnuncioId' => '10',
           'user_id' => '1',
             'citta' => 'Ancona',               
             'zona_quartiere' => 'Q2',
             'indirizzo' => 'via flavia 25',
             'descrizione' => 'camera spaziosa',
             'importo' => '220',
             'dimensione' => '18',
             'tipologia' => 'Posto Letto',
             'data_inizio_disponibilita' => date("2022-02-17"),
             'data_fine_disponibilita' => date("2023-03-17"),
             'servizi_inclusi' => 'lavastoviglie garage',
             'eta_minima' => '19',
             'genere_richiesto' => null,
             'assegnato' => '0',               
             'data_assegnazione' => null,
             'immagine' => '2.jpg',
             'C_numero_posti_letto_totali' => '1',
             'C_numero_posti_letto_in_camera' => '1',
             'C_presenza_angolo_studio' => '1',
             'A_numero_camere' => null,
             'A_numero_posti_letto' => null,
             'A_presenza_cucina' => null,
             'A_presenza_locale_ricreativo' => null,
             'A_servizi_disponibili' => 'parcheggio',
             'created_at' => date("Y-m-d H:i:s"),
             'updated_at' => date("Y-m-d H:i:s")],
            
            ['AnnuncioId' => '11',
             'user_id' => '1',
             'citta' => 'Ancona',               
             'zona_quartiere' => 'Q2',
             'indirizzo' => 'via flavia 25',
             'descrizione' => 'camera spaziosa',
             'importo' => '220',
             'dimensione' => '18',
             'tipologia' => 'Posto Letto',
             'data_inizio_disponibilita' => date("2022-02-17"),
             'data_fine_disponibilita' => date("2023-03-17"),
             'servizi_inclusi' => 'lavastoviglie garage',
             'eta_minima' => '19',
             'genere_richiesto' => null,
             'assegnato' => '0',               
             'data_assegnazione' => null,
             'immagine' => '1.jpg',
             'C_numero_posti_letto_totali' => '1',
             'C_numero_posti_letto_in_camera' => '1',
             'C_presenza_angolo_studio' => '1',
             'A_numero_camere' => null,
             'A_numero_posti_letto' => null,
             'A_presenza_cucina' => null,
             'A_presenza_locale_ricreativo' => null,
             'A_servizi_disponibili' => 'parcheggio',
             'created_at' => date("Y-m-d H:i:s"),
             'updated_at' => date("Y-m-d H:i:s")],
           
            
            ['AnnuncioId' => '12',
            'user_id' => '1',
             'citta' => 'Ancona',               
             'zona_quartiere' => 'Q2',
             'indirizzo' => 'via flavia 25',
             'descrizione' => 'camera spaziosa',
             'importo' => '220',
             'dimensione' => '18',
             'tipologia' => 'Posto Letto',
             'data_inizio_disponibilita' => date("2022-02-17"),
             'data_fine_disponibilita' => date("2023-03-17"),
             'servizi_inclusi' => 'lavastoviglie garage',
             'eta_minima' => '19',
             'genere_richiesto' => null,
             'assegnato' => '0',               
             'data_assegnazione' => null,
             'immagine' => '3.jpg',
             'C_numero_posti_letto_totali' => '1',
             'C_numero_posti_letto_in_camera' => '1',
             'C_presenza_angolo_studio' => '1',
             'A_numero_camere' => null,
             'A_numero_posti_letto' => null,
             'A_presenza_cucina' => null,
             'A_presenza_locale_ricreativo' => null,
             'A_servizi_disponibili' => 'parcheggio',
             'created_at' => date("Y-m-d H:i:s"),
             'updated_at' => date("Y-m-d H:i:s")],
            
        ]);

        DB::table('faq')->insert([
            ['FaqId' => '1',
             'domanda' => 'Come posso inserire un mio appartamento?',
             'risposta' => 'Per inserire un annuncio è sufficiente cliccare sulla voce "Crea annuncio"',               
             'created_at' => date("Y-m-d H:i:s"),
             'updated_at' => date("Y-m-d H:i:s")],
            
            ['FaqId' => '2',
             'domanda' => 'Come faccio ad opzionare un offerta?',
             'risposta' => 'Per opzionare un offerta desiderata è necessario registrarsi come locatario/studente ed accedere nella scheda alloggio desiderata ed infine cliccare il pulsante "opziona offerta" ',               
             'created_at' => date("Y-m-d H:i:s"),
             'updated_at' => date("Y-m-d H:i:s")],
            
            ['FaqId' => '3',
             'domanda' => 'Come faccio a filtrare le offerte?',
             'risposta' => 'Registrandosi come loatario/studente si accede alla funzionalità di filtraggio',               
             'created_at' => date("Y-m-d H:i:s"),
             'updated_at' => date("Y-m-d H:i:s")],
            
            ['FaqId' => '4',
             'domanda' => 'Chi siete?',
             'risposta' => 'Renthem',               
             'created_at' => date("Y-m-d H:i:s"),
             'updated_at' => date("Y-m-d H:i:s")],
        ]);
        
        DB::table('messaggi')->insert([
            ['ID' => '1',
             'IDmittente' => '2',
             'IDdestinatario' => '1', 
             'contenuto' => 'Salve vorrei sapere di più sull annuncio', 
             'IDannuncio' => '1', 
             'created_at' => date("Y-m-d H:i:s"),
             'updated_at' => date("Y-m-d H:i:s")],
            
            ['ID' => '2',
             'IDmittente' => '1',
             'IDdestinatario' => '2', 
             'contenuto' => 'L annuncio riguarda l appartamento', 
             'IDannuncio' => '1', 
             'created_at' => date("Y-m-d H:i:s"),
             'updated_at' => date("Y-m-d H:i:s")],
            
            ['ID' => '3',
             'IDmittente' => '2',
             'IDdestinatario' => '1', 
             'contenuto' => 'Salve vorrei sapere di più sull annuncio', 
             'IDannuncio' => '2', 
             'created_at' => date("Y-m-d H:i:s"),
             'updated_at' => date("Y-m-d H:i:s")],
            
            ['ID' => '4',
             'IDmittente' => '1',
             'IDdestinatario' => '2', 
             'contenuto' => 'L annuncio riguarda la camera', 
             'IDannuncio' => '2', 
             'created_at' => date("Y-m-d H:i:s"),
             'updated_at' => date("Y-m-d H:i:s")],
        ]);
    }

}
